-- MySQL Script generated by MySQL Workbench
-- Tue Apr  1 18:50:21 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SeaPort
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SeaPort
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SeaPort` DEFAULT CHARACTER SET utf8 ;
USE `SeaPort` ;

-- -----------------------------------------------------
-- Table `SeaPort`.`ВидСудна`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SeaPort`.`ВидСудна` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ВидСудна` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ВидСудна_UNIQUE` (`ВидСудна` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SeaPort`.`Судно`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SeaPort`.`Судно` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `НазваниеСудна` VARCHAR(30) NOT NULL,
  `idВида` INT NOT NULL,
  `ТоннажСудна` INT NOT NULL,
  INDEX `fk_вид_idx` (`idВида` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_вид`
    FOREIGN KEY (`idВида`)
    REFERENCES `SeaPort`.`ВидСудна` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SeaPort`.`Швартовка`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SeaPort`.`Швартовка` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idСудна` INT NOT NULL,
  `ДатаШвартовки` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_судно_idx` (`idСудна` ASC) VISIBLE,
  CONSTRAINT `fk_судно`
    FOREIGN KEY (`idСудна`)
    REFERENCES `SeaPort`.`Судно` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
