-- MySQL Script generated by MySQL Workbench
-- Mon Apr 28 17:32:56 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sea_port
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sea_port
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sea_port` DEFAULT CHARACTER SET utf8 ;
USE `sea_port` ;

-- -----------------------------------------------------
-- Table `sea_port`.`shipType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sea_port`.`shipType` (
  `id` INT NOT NULL,
  `type_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `type_name_UNIQUE` (`type_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sea_port`.`ship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sea_port`.`ship` (
  `id` INT NOT NULL,
  `ship_name` VARCHAR(45) NOT NULL,
  `idType` INT NOT NULL,
  `ship_tonnage` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ship_name_UNIQUE` (`ship_name` ASC) VISIBLE,
  INDEX `fk_ship_idx` (`idType` ASC) VISIBLE,
  CONSTRAINT `fk_ship`
    FOREIGN KEY (`idType`)
    REFERENCES `sea_port`.`shipType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sea_port`.`mooring`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sea_port`.`mooring` (
  `id` INT NOT NULL,
  `idShip` INT NOT NULL,
  `mooring_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_mooring_idx` (`idShip` ASC) VISIBLE,
  CONSTRAINT `fk_mooring`
    FOREIGN KEY (`idShip`)
    REFERENCES `sea_port`.`ship` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
